[Configuration]
BackgroundMode=TERMINAL_BACKGROUND_TRANSPARENT
BackgroundDarkness=0.90
ColorForeground=#00e5ff
ColorBackground=#050510
ColorCursor=#00e5ff
ColorCursorUseDefault=FALSE
ColorPalette=#1a1a2e;#ff1744;#00e676;#ffea00;#2979ff;#e040fb;#00b4d4;#e0e0e0;#424242;#ff5252;#69f0ae;#ffff00;#448aff;#ea80fc;#18ffff;#ffffff
MiscDefaultGeometry=100x30
MiscHighlightUrls=TRUE
FontName=JetBrains Mono 11
FontUseSystem=FALSE
ScrollingBar=TERMINAL_SCROLLBAR_NONE
TabActivityColor=#00e5ff
